name: Integration test with mediamtx stream

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo add-apt-repository universe &&
        sudo apt-get install -y libswscale-dev libavcodec-dev libavformat-dev libavutil-dev ffmpeg libfuse2
        
    - name: Download and extract mediamtx
      run: |
        wget https://github.com/bluenviron/mediamtx/releases/download/v1.6.0/mediamtx_v1.6.0_linux_amd64.tar.gz
        tar -xzf mediamtx_v1.6.0_linux_amd64.tar.gz
        
    - name: Run mediamtx
      run: ./mediamtx &
      
    - name: Run fake RTSP camera
      run: ffmpeg -re -f lavfi -i testsrc=size=640x480:rate=30 -vcodec libx264 -pix_fmt yuv420p -f rtsp -rtsp_transport tcp rtsp://0.0.0.0:8554/live.stream &
      
    - name: Build viamrtsp binary
      run: make bin/viamrtsp
      
    - name: Install viam-server
      run: |
        curl https://storage.googleapis.com/packages.viam.com/apps/viam-server/viam-server-stable-x86_64.AppImage -o viam-server
        chmod 755 viam-server
        sudo ./viam-server --aix-install
        
    - name: Add viam-server config
      run: |
        cat << EOF > integration-test-config.json
        {
          "model": "erh:viamrtsp:rtsp",
          "name": "ip-cam",
          "namespace": "rdk",
          "type": "camera",
          "attributes": {
            "rtsp_address": "rtsp://localhost:8554/live.stream"
          },
          "depends_on": []
        }
        EOF
        
    - name: Run viam-server
      run: viam-server -debug -config ./integration-test-config.json &

    - name: Build test client binary and run test client script
      run: |
        go build -o testClient ./testClient.go
        chmod +x ./testClient
        ./testClient
