name: Format and lint

on:
    push:
      branches:
        - main
      paths:
        - '**/*.go'
    pull_request:
      paths:
        - '**/*.go'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Check gofmt
      run: |
        UNFORMATTED=$(gofmt -l .)
        if [ -n "$UNFORMATTED" ]; then
          echo "Some files are not gofmt'd:"
          echo $UNFORMATTED
          exit 1  # Exit with a status of 1 to indicate error
        else
          echo "All files are properly formatted."
        fi
    
    - name: Run linter and static checks
      run: make lint
